### ISSUE TITLE
how to render the environment

### ISSUE THREAD

**Issue by dzy666fly** [prasuchit/Dec-AIRL#1]
Thank u so much for sharing the code!
Luckily, I run the three scripts successfully given in the `README.md`. Since I am not familiar to the environment, I don't know how to visualize the environment during the training and the rollout phases. Could u give me some advice or documents on how to render it?
Looking forward to your reply.

**Comment by prasuchit** [comment]
@dzy666fly with the assistive gym policy, you can follow their readme on how to load trained policy weights to visualize it. With the HRC domain, since it's a real-world domain, there's no rendering for it, however, you can set verbose=true in the step function of the environment to print out the states and actions of both agents.

**Comment by dzy666fly** [comment]
Thank u so much for timely reply. I have run the task FeedingSaywerHuman-v1 successfully in several days even with gpu,  is it normal? And with `test_irl.py` the environment can be visualized. I will try to compare the result with Co-GAIL as done in the paper, as well as consider how to use Dec-AIRL on our real-world Co-carry HRC task.
